FROM openwrtorg/sdk:mvebu-cortexa9-19.07.7

#RUN apt-get update && \
#    apt-get install -y \
#        g++ \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*
COPY feeds.conf.default /home/build/openwrt/

#EXPOSE 4000

#WORKDIR /tmp

#ENTRYPOINT [ "bundle", "exec", "" ]

#CMD ["/sbin/bash","","",""]
