

default:
	@echo "No default rule. Use: 'build' or 'push'"

build:
#	docker build -t a-docker-registry.whatever/whatever/path/image-name .
	docker build -t tmkwl/openwrt-sdk-19.07.7-mvebu-cortexa9 .

push:
#	docker push a-docker-registry.whatever/whatever/path/image-name
	docker push tmkwl/openwrt-sdk-19.07.7-mvebu-cortexa9
